services:
  - type: web
    name: broadlocal
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: APP_BASE_URL
        value: https://broadlocal.com
      - key: STRIPE_SECRET_KEY
        sync: false
